
name: sim_bridge
description: SIM Bridge _ Manage your second phone from iPhone. Remote SMS, Calls & Data.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.0
  firebase_auth: ^4.15.0
  firebase_database: ^10.4.0
  permission_handler: ^11.1.0
  telephony: ^0.2.0
  flutter_webrtc: ^0.9.48
  shared_preferences: ^2.2.2

flutter:
  uses_material_design: true
